Script started on Tue 03 Nov 2015 06:13:47 PM PST
randyhe@Y510P:~/Documents/FALL2015/CS100/rshell$ makershell
rm -rfv bin
removed ‘bin/rshell’
removed directory: ‘bin’
mkdir -p bin
g++ -Wall -Werror -ansi -pedantic -I boost_1_59_0 src/main.cpp src/Connector.cpp src/Or.cpp src/And.cpp src/Semicolon.cpp src/Run.cpp src/Parse.cpp -o bin/rshell
randyhe@Y510P:~/Documents/FALL2015/CS100/rshell$ bin/rshell
randyhe@Y510P$ echo #ehey

randyhe@Y510P$ echo #hey

randyhe@Y510P$ echo hashtags#inside#words#are#not#comments!
hashtags#inside#words#are#not#comments!
randyhe@Y510P$ echo #eworksiby itself

randyhe@Y510P$ echo #works in front!of

randyhe@Y510P$ echo hashtags#behind#words#are#not#comments#either && echo hey
hashtags#behind#words#are#not#comments#either
hey
randyhe@Y510P$ echo hey# && echo world
hey#
world
randyhe@Y510P$ echo #ehey &&eecho testing commentingpwith multiple commands

randyhe@Y510P$ echo #hey && echo should not output

randyhe@Y510P$ ls #-al-le
bin  boost_1_59_0  LICENSE  Makefile  README.md  src  tests  typescript
randyhe@Y510P$ ls -a #-l
.  ..  bin  boost_1_59_0  .git	LICENSE  Makefile  README.md  src  tests  typescript
randyhe@Y510P$ exit
randyhe@Y510P:~/Documents/FALL2015/CS100/rshell$ exit
exit

Script done on Tue 03 Nov 2015 06:16:26 PM PST
