Script started on Tue 03 Nov 2015 06:03:57 PM PST
randyhe@Y510P:~/Documents/FALL2015/CS100/rshell$ make
rm -rfv bin
mkdir -p bin
g++ -Wall -Werror -ansi -pedantic -I boost_1_59_0 src/main.cpp src/Connector.cpp src/Or.cpp src/And.cpp src/Semicolon.cpp src/Run.cpp src/Parse.cpp -o bin/rshell
randyhe@Y510P:~/Documents/FALL2015/CS100/rshell$ bin/rshell
randyhe@Y510P$ ls;opwd;
bin  boost_1_59_0  LICENSE  Makefile  README.md  src  tests  typescript
/home/randyhe/Documents/FALL2015/CS100/rshell
randyhe@Y510P$ ls; pwd
bin  boost_1_59_0  LICENSE  Makefile  README.md  src  tests  typescript
/home/randyhe/Documents/FALL2015/CS100/rshell
randyhe@Y510P$ ls ;pwd
bin  boost_1_59_0  LICENSE  Makefile  README.md  src  tests  typescript
/home/randyhe/Documents/FALL2015/CS100/rshell
randyhe@Y510P$ ls;pwd
bin  boost_1_59_0  LICENSE  Makefile  README.md  src  tests  typescript
/home/randyhe/Documents/FALL2015/CS100/rshell
randyhe@Y510P$ ls	 ; pwd
bin  boost_1_59_0  LICENSE  Makefile  README.md  src  tests  typescript
/home/randyhe/Documents/FALL2015/CS100/rshell
randyhe@Y510P$ ls	     ; pwd ;
bin  boost_1_59_0  LICENSE  Makefile  README.md  src  tests  typescript
/home/randyhe/Documents/FALL2015/CS100/rshell
randyhe@Y510P$ ls && pwd
bin  boost_1_59_0  LICENSE  Makefile  README.md  src  tests  typescript
/home/randyhe/Documents/FALL2015/CS100/rshell
randyhe@Y510P$ badinput && lsd
execvp failed: No such file or directory
randyhe@Y510P$ badinput&&&ls
execvp failed: No such file or directory
randyhe@Y510P$ badinput &&ls
execvp failed: No such file or directory
randyhe@Y510P$ true && ls
bin  boost_1_59_0  LICENSE  Makefile  README.md  src  tests  typescript
randyhe@Y510P$ echo hello && echo world
hello
world
randyhe@Y510P$ echo hello	    &&echo world
hello
world
randyhe@Y510P$ echo hello&&echo world
hello
world
randyhe@Y510P$ echo hello||echo world
hello
randyhe@Y510P$ echo hello|| echo world
hello
randyhe@Y510P$ echo hello ||echo world
hello
randyhe@Y510P$ echo hello	     || echo world
hello
randyhe@Y510P$ echo hello &&& echo world
Error: Invalid Syntax.
randyhe@Y510P$ echo hello &&&&&& echooworld
Error: Invalid Syntax.
randyhe@Y510P$ echo hello ||||||| echo world
Error: Invalid Syntax.
randyhe@Y510P$ echo hello | echo world
Error: Invalid Syntax.
randyhe@Y510P$ echo hello & echo world
Error: Invalid Syntax.
randyhe@Y510P$ &&eecho hello
Error: Invalid Syntax.
randyhe@Y510P$ || echo hello
Error: Invalid Syntax.
randyhe@Y510P$ ; echo hello
Error: Invalid Syntax.
randyhe@Y510P$ ;;;; echo hello
Error: Invalid Syntax.
randyhe@Y510P$ &&& echo hello
Error: Invalid Syntax.
randyhe@Y510P$ ||| echo hello
Error: Invalid Syntax.
randyhe@Y510P$ echo    hello	      &&&echo	 echo hello
hello
hello
randyhe@Y510P$ echo hey; echo i; echo like; echo ucr;
hey
i
like
ucr
randyhe@Y510P$ echo hey && echo no || echo what
hey
no
randyhe@Y510P$ false && false || echo hey
hey
randyhe@Y510P$ truee&& true || echo nothing
randyhe@Y510P$ exit
randyhe@Y510P:~/Documents/FALL2015/CS100/rshell$ exit
exit

Script done on Tue 03 Nov 2015 06:07:48 PM PST
