Script started on Tue 03 Nov 2015 06:11:12 PM PST
randyhe@Y510P:~/Documents/FALL2015/CS100/rshell$ make
rm -rfv bin
removed ‘bin/rshell’
removed directory: ‘bin’
mkdir -p bin
g++ -Wall -Werror -ansi -pedantic -I boost_1_59_0 src/main.cpp src/Connector.cpp src/Or.cpp src/And.cpp src/Semicolon.cpp src/Run.cpp src/Parse.cpp -o bin/rshell
randyhe@Y510P:~/Documents/FALL2015/CS100/rshell$ bin/rshell
randyhe@Y510P$ echo histinggone lin
hi
randyhe@Y510P$ echo		   testing whitespace
testing whitespace
randyhe@Y510P$ echo						    that'saallotoofwwhitespaces!
that's a lot of whitespaces!
randyhe@Y510P$ mkdir testDirectory
randyhe@Y510P$ ls
bin  boost_1_59_0  LICENSE  Makefile  README.md  src  testDirectory  tests  typescript
randyhe@Y510P$ rm -r testDirectory
randyhe@Y510P$ ls
bin  boost_1_59_0  LICENSE  Makefile  README.md  src  tests  typescript
randyhe@Y510P$ date
Tue Nov  3 18:12:02 PST 2015
randyhe@Y510P$ pwd
/home/randyhe/Documents/FALL2015/CS100/rshell
randyhe@Y510P$ echo "Everythinglinnquotes is one argument!"
Everything in quotes is one argument!
randyhe@Y510P$ echo "Hello" "World" "!!!"e Arguments
Hello World !!!
randyhe@Y510P$ cal
   November 2015
Su Mo Tu We Th Fr Sa
 1  2  3  4  5	6  7
 8  9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30

randyhe@Y510P$ exit
randyhe@Y510P:~/Documents/FALL2015/CS100/rshell$ exit
exit

Script done on Tue 03 Nov 2015 06:12:45 PM PST
